version: 0.2

phases:
  build:
    commands:
      - pwd
      - ls
      - env
      - python -m venv .venv && . ./venv/bin/source && pip install -r requirements.txt
      - cdk diff CdkApigwLambdaStack
      - cdk deploy CdkApigwLambdaStack
