version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - echo installing cfn-nag
      - gem install cfn-nag
  build:
    commands:
      - pwd
      - ls
      - npm -v
      - env
      - npm install -g aws-cdk
      - python -m venv .venv && ls -ltr .venv/bin && . .venv/bin/activate && pip install -r requirements.txt
      - cdk synth --all
      - mkdir report
      - SCAN_RESULT=$(cfn_nag_scan --fail-on-warnings --input-path  cdk.out/ -o json > ./report/cfn_nag.out.json && echo OK || echo FAILED)
      - ls -ltr report
      - cdk diff CdkApigwLambdaStack
      - cdk deploy CdkApigwLambdaStack --require-approval never
