version: 0.2

phases:
  build:
    commands:
      - pwd
      - ls
      - npm -v
      - env
      - npm install -g aws-cdk
      - python -m venv .venv && ls -ltr .venv/ && source ./venv/bin/activate && pip install -r requirements.txt
      - cdk diff CdkApigwLambdaStack
      - cdk deploy CdkApigwLambdaStack
